Add user_data_replace_on_change
cloudposse/terraform-aws-ec2-instance pull request #123
Opened 2022-03-25 18:25 UTC by bwmetcalf

## what
* Add `user_data_replace_on_change` parameter to allow rebuilding of instances when user data changes.

## why
* Setting `user_data_replace_on_change` to `true` will restore old behavior.

## references
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change

2022-03-25 18:36 UTC, woz5999 commented on main.tf
> +  user_data_replace_on_change          = var.user_data_replace_on_change
It looks like you may need to add a comment to skip this check since it seems unrelated to your changes.

2022-03-25 18:47 UTC, woz5999 commented
/test all

2022-03-25 18:47 UTC, woz5999 approved these changes
lgtm

2022-03-29 00:48 UTC, Nuru requested changes
Among other things, let's not require AWS provider v4 yet.

2022-03-29 02:05 UTC, bwmetcalf commented
> Among other things, let's not require AWS provider v4 yet.

OK.  4.7.0 of the provider is the earliest version that supports  `user_data_replace_on_change`, so I'll leave this open for now.

2024-03-13 19:47 UTC, bwmetcalf commented
/open

2024-03-14 00:37 UTC, Gowiem commented
@bwmetcalf want to work through the conflicts and rebuild README (via `make init && make readme`) and we'll work on this one? I saw you comment `/open` and this looks like a legit change, so I saw we push it forward. Make those changes and ping me when you're ready!

2024-03-19 19:46 UTC, closed without merging