feat(aws_instance): add ignore_ami_changes option
cloudposse/terraform-aws-ec2-instance pull request #209
Opened 2024-09-06 10:39 UTC by Lawstorant

## what

Allow ignoring AMI image ID changes. EC2 instance won't be recreated If the AMI image id is provided from a data source changes.

## why

We use an aws_ami data Blocks that always provides the most recent version of selected image but that will cause the EC2 to recreate if the image is updated. We want to be able to upgrade only when we see fit.

2024-09-06 13:25 UTC, nitrocode requested changes
See comments

2024-09-06 13:27 UTC, nitrocode commented
Thanks for the pr @Lawstorant. Instead of updating the module, have you considered simply setting the `ami` input of the module? That should prevent your ec2 from getting recreated

2024-10-01 13:11 UTC, Lawstorant commented on main.tf
> +    ignore_changes = var.ignore_ami_changes ? [ami] : []
You're right

2024-10-01 13:12 UTC, Lawstorant commented
My problem is that I'm setting the ami input already, but the input data comes from a filter in a data source. Well, I'm going to filter it better and close this for now.

2024-10-01 13:12 UTC, closed without merging