Remove use of deprecated null_data_source
cloudposse/terraform-aws-ec2-instance pull request #94
Opened 2021-04-20 17:12 UTC by bwmetcalf

Moved logic from null_data_source into definition of locals.public_dns.

null_data_source is now deprecated (using tf 0.14.5) and throws warnings.  See PR below.

https://registry.terraform.io/providers/hashicorp/null/latest/docs/data-sources/data_source
https://github.com/cloudposse/terraform-aws-ec2-instance/issues/93

2021-04-20 18:26 UTC, woz5999 commented
/rebuild-readme

2021-04-20 18:26 UTC, woz5999 commented
/test all

2021-04-20 18:35 UTC, woz5999 commented on main.tf
>  resource "aws_ebs_volume" "default" {
this seems to be a false positive? In any case, it's unrelated to the changes in this PR.

2021-04-20 19:35 UTC, Gowiem commented
@bwmetcalf our CI got stuck which happens sometimes. Can you push an empty commit like so: 

```bash
git commit --allow-empty -m "Trigger CI"
git push
```

That will trigger that last required build and then @woz5999 can take it from here 👍

2021-04-23 15:10 UTC, bwmetcalf commented
@Gowiem Hey Matt, anything else I need to do on this to get it merged?  Thanks.

2021-04-23 15:13 UTC, woz5999 commented
/test all

2021-04-23 15:56 UTC, woz5999 commented
@Gowiem I'm not sure of the solution to the Bridgecrew analysis failure. It's unrelated to this change and seems to be invalid regardless.

2021-04-23 15:58 UTC, Gowiem commented
@woz5999 agreed. Let's get @maximmi or @Nuru thoughts on the matter. They're more involved in the BridgeCrew work than I am.

Gents, do we need to hold off merging this PR? It seems the BridgeCrew CI is failing on this PR due to something that is already merged into master. How are we handling that elsewhere?

2021-04-23 18:18 UTC, jwstric2 commented
hi team, I hit a similar issue on https://github.com/cloudposse/terraform-aws-alb/pull/86, drew the short straw as a PR that went in after enhancements to code analysis.  it's definitely new changes to the analytics of bridgecrew as I was able to pull an old container and never saw the results produced in the new containers.  Seems the consensus is skips if they make sense to skip ...

2021-04-25 05:50 UTC, Nuru commented on main.tf
>  resource "aws_ebs_volume" "default" {
Yes, don't worry about this bridgecrew warning

2021-04-25 06:05 UTC, Nuru requested changes
Do not worry about the Bridgecrew warning/complaint, but please simplify the `public_dns` expression. I made a suggestion but have not double-checked it for accuracy.

2021-04-25 06:05 UTC, Nuru commented on main.tf
> +  join("", aws_instance.default.*.public_dns))
While I appreciate the effort, this is really hard to read. Let's use local variables to simplify the expression.
```suggestion

  region_domain  = local.region == "us-east-1" ? "compute-1.amazonaws.com" : "${local.region}.compute.amazonaws.com"
  eip_public_dns = "ec2-${replace(join("", aws_eip.default.*.public_ip), ".", "-")}.${local.region_domain}"
  public_dns     = (
    var.associate_public_ip_address && var.assign_eip_address && module.this.enabled ?
    local.eip_public_dns : join("", aws_instance.default.*.public_dns)
  )
```

2021-04-26 17:56 UTC, woz5999 approved these changes

2021-04-26 17:56 UTC, woz5999 commented
/test all

2021-04-26 18:16 UTC, woz5999 commented
@Gowiem I think this is ready to go

2021-04-26 23:07 UTC, Gowiem approved these changes

2021-04-26 23:08 UTC, merged

2021-04-26 23:09 UTC, Gowiem commented
Thanks for the contribution @bwmetcalf (and help @jwstric2 + @woz5999)! Released as [0.31.0](https://github.com/cloudposse/terraform-aws-ec2-instance/releases/tag/0.31.0).